{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-backend-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  database_url: {{ .Values.backend.secrets.database_url | quote }}
  better_auth_secret: {{ .Values.backend.secrets.better_auth_secret | quote }}
  openai_api_key: {{ .Values.backend.secrets.openai_api_key | quote }}
  gemini_api_key: {{ .Values.backend.secrets.gemini_api_key | quote }}
{{- end }}

